<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8" %>
<%@ include file="/mobilefirst/include/Base_Inc_Mobile.jsp"%>
<%@page import="org.apache.commons.lang3.StringUtils"%>
<%@page import="org.json.*"%>
<%
    JSONArray jSONArray = new JSONArray();
    JSONObject jSONObject = new JSONObject();
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170103");
    jSONObject.put("company","KFC");
    jSONObject.put("giftName","징거버거 세트");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift01.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit",5500);
    jSONObject.put("price",55000);
    jSONObject.put("quiz","2016 에누리 10대 히트상품 중 득표수 1위를 차지한 상품은 무엇일까요?");
    jSONObject.put("ex1","샤오미 보조배터리 10000mAh");
    jSONObject.put("ex2","삼성 기어 S3 프론티어 LTE");
    jSONObject.put("ex3","LG 그램 15ZD960-GX50K");
    jSONObject.put("answer",2);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170104");
    jSONObject.put("company","또래오래");
    jSONObject.put("giftName","오곡후라이드치킨+콜라1.25L");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift02.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 16500);
    jSONObject.put("price",165000);
    jSONObject.put("quiz","2016 에누리 10대 히트상품 중 판매량이 가장 많았던 상품은 무엇일까요?");
    jSONObject.put("ex1","샤오미 보조배터리 10000mAh");
    jSONObject.put("ex2","제주 삼다수 생수 2L");
    jSONObject.put("ex3","더블에이 복사지 A4 80g");
    jSONObject.put("answer",1);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170105");
    jSONObject.put("company","해피머니");
    jSONObject.put("giftName","해피머니 상품권 5천원권");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift03.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit",  5000);
    jSONObject.put("price", 50000);
    jSONObject.put("quiz","15.6형 대화면에서 여전히 980g의 무게! 그램15의 대표모델은?");
    jSONObject.put("ex1","LG 그램 13ZD950-GX56K");
    jSONObject.put("ex2","LG 그램 14ZD960-GX58K");
    jSONObject.put("ex3","LG 그램 15ZD960-GX50K");
    jSONObject.put("answer",3);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170106");
    jSONObject.put("company","던킨도너츠");
    jSONObject.put("giftName","커피&도넛 2개");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift04.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit",  5600);
    jSONObject.put("price", 56000);
    jSONObject.put("quiz","블루투스 무선 연결, 내장배터리로 캠핑장에서도 활용가능한 프로젝터는?");
    jSONObject.put("ex1","고프로 HERO5 블랙");
    jSONObject.put("ex2","LG 미니빔 PH550");
    jSONObject.put("ex3","삼성 UN60J6350AF");
    jSONObject.put("answer",2);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170107");
    jSONObject.put("company","베스킨라빈스");
    jSONObject.put("giftName","싱글킹 아이스크림");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift05.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 3500);
    jSONObject.put("price",  35000);
    jSONObject.put("quiz","2016년 가장 사랑받은 메탈디자인 830L 양문형 냉장고는?");
    jSONObject.put("ex1","LG 디오스 S835SD32");
    jSONObject.put("ex2","LG 디오스 R-F915HBSS");
    jSONObject.put("ex3","LG 디오스 F877SS32");
    jSONObject.put("answer",1);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170108");
    jSONObject.put("company","베스킨라빈스");
    jSONObject.put("giftName","싱글킹 아이스크림");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift05.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 3500);
    jSONObject.put("price",  35000);
    jSONObject.put("quiz","자연스럽고 부드러운 화질을 구현하는 내추럴 블랙패널 60인치 TV는?");
    jSONObject.put("ex1","LG 58UH6600");
    jSONObject.put("ex2","삼성 UN65J6350AF");
    jSONObject.put("ex3","삼성 UN60J6350AF");
    jSONObject.put("answer",3);
    jSONArray.put(jSONObject);
        
    jSONObject = new JSONObject();
    jSONObject.put("date","20170109");
    jSONObject.put("company","스타벅스");
    jSONObject.put("giftName","카페아메리카노 Tall");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift06.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 4100);
    jSONObject.put("price",  41000);
    jSONObject.put("quiz","디자인과 자동모드가 업그레이드된 2017년형 프리미엄 안마의자는?");
    jSONObject.put("ex1","바디프랜드 팬텀");
    jSONObject.put("ex2","바디프랜드 NEW 파라오");
    jSONObject.put("ex3","휴테크산업 루씨르");
    jSONObject.put("answer",2);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170110");
    jSONObject.put("company","KFC");
    jSONObject.put("giftName","징거버거 세트");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift01.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 5500);
    jSONObject.put("price",  55000);
    jSONObject.put("quiz","온가족이 편리하게 사용가능한 멀티 유저 모드를 갖춘 태블릿PC는?");
    jSONObject.put("ex1","삼성 갤럭시탭A 2016");
    jSONObject.put("ex2","LG G패드3 8.0");
    jSONObject.put("ex3","애플 아이패드 프로 9.7");
    jSONObject.put("answer",1);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170111");
    jSONObject.put("company","KFC");
    jSONObject.put("giftName","먼치킨 10개팩");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift07.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 3000);
    jSONObject.put("price",  30000);
    jSONObject.put("quiz","PBP, 피봇 기능을 갖춘 UHD 초고해상도 화면의 27형 모니터는?");
    jSONObject.put("ex1","삼성 C27F390");
    jSONObject.put("ex2","뷰소닉 VX2776");
    jSONObject.put("ex3","LG 27UD88");
    jSONObject.put("answer",3);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170112");
    jSONObject.put("company","카페베네");
    jSONObject.put("giftName","라떼 R-Size");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift08.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 4600);
    jSONObject.put("price",  46000);
    jSONObject.put("quiz"," 2016 에누리 10대 히트상품 중 득표수 1위를 차지한 상품은 무엇일까요?");
    jSONObject.put("ex1","샤오미 보조배터리 10000mAh");
    jSONObject.put("ex2","삼성 기어 S3 프론티어 LTE");
    jSONObject.put("ex3","LG 그램 15ZD960-GX50K");
    jSONObject.put("answer",2);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170113");
    jSONObject.put("company","던킨도너츠");
    jSONObject.put("giftName","도넛3개");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift09.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 3900);
    jSONObject.put("price",  39000);
    jSONObject.put("quiz","2016 에누리 10대 히트상품 중 판매량이 가장 많았던 상품은 무엇일까요?");
    jSONObject.put("ex1","샤오미 보조배터리 10000mAh");
    jSONObject.put("ex2","제주 삼다수 생수 2L");
    jSONObject.put("ex3","더블에이 복사지 A4 80g");
    jSONObject.put("answer",1);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170114");
    jSONObject.put("company","GS25");
    jSONObject.put("giftName","GS25 모바일 상품권 3천원권");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift10.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 3000);
    jSONObject.put("price",  30000);
    jSONObject.put("quiz","15.6형 대화면에서 여전히 980g의 무게! 그램15의 대표모델은?");
    jSONObject.put("ex1","LG 그램 13ZD950-GX56K");
    jSONObject.put("ex2","LG 그램 14ZD960-GX58K");
    jSONObject.put("ex3","LG 그램 15ZD960-GX50K");
    jSONObject.put("answer",3);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170115");
    jSONObject.put("company","GS25");
    jSONObject.put("giftName","GS25 모바일 상품권 3천원권");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift10.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 3000);
    jSONObject.put("price",  30000);
    jSONObject.put("quiz","블루투스 무선 연결, 내장배터리로 캠핑장에서도 활용가능한 프로젝터는?");
    jSONObject.put("ex1","고프로 HERO5 블랙");
    jSONObject.put("ex2","LG 미니빔 PH550");
    jSONObject.put("ex3","삼성 UN60J6350AF");
    jSONObject.put("answer",2);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170116");
    jSONObject.put("company","롯데리아");
    jSONObject.put("giftName","치킨버거 세트");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift11.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 5100);
    jSONObject.put("price",  51000);
    jSONObject.put("quiz","2016년 가장 사랑받은 메탈디자인 830L 양문형 냉장고는?");
    jSONObject.put("ex1","LG 디오스 S835SD32");
    jSONObject.put("ex2","LG 디오스 R-F915HBSS");
    jSONObject.put("ex3","LG 디오스 F877SS32");
    jSONObject.put("answer",1);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170117");
    jSONObject.put("company","던킨도너츠");
    jSONObject.put("giftName","도넛3개");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift09.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 3900);
    jSONObject.put("price",  39000);
    jSONObject.put("quiz","자연스럽고 부드러운 화질을 구현하는 내추럴 블랙패널 60인치 TV는?");
    jSONObject.put("ex1","LG 58UH6600");
    jSONObject.put("ex2","삼성 UN65J6350AF");
    jSONObject.put("ex3","삼성 UN60J6350AF");
    jSONObject.put("answer",3);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170118");
    jSONObject.put("company","CU");
    jSONObject.put("giftName","CU 모바일 상품권 5천원권");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift12.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 5000);
    jSONObject.put("price",  50000);
    jSONObject.put("quiz","디자인과 자동모드가 업그레이드된 2017년형 프리미엄 안마의자는?");
    jSONObject.put("ex1","바디프랜드 팬텀");
    jSONObject.put("ex2","바디프랜드 NEW 파라오");
    jSONObject.put("ex3","휴테크산업 루씨르");
    jSONObject.put("answer",2);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170119");
    jSONObject.put("company","스타벅스");
    jSONObject.put("giftName","카페아메리카노 Tall");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift06.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit", 4100);
    jSONObject.put("price",  41000);
    jSONObject.put("quiz","온가족이 편리하게 사용가능한 멀티 유저 모드를 갖춘 태블릿PC는?");
    jSONObject.put("ex1","삼성 갤럭시탭A 2016");
    jSONObject.put("ex2","LG G패드3 8.0");
    jSONObject.put("ex3","애플 아이패드 프로 9.7");
    jSONObject.put("answer",1);
    jSONArray.put(jSONObject);
    
    jSONObject = new JSONObject();
    jSONObject.put("date","20170120");
    jSONObject.put("company","멕시카나 치킨");
    jSONObject.put("giftName","후라이드+콜라 1.25L");
    jSONObject.put("gift_img","http://imgenuri.enuri.gscdn.com/images/event/2016/m_hit/gift13.png");
    jSONObject.put("cnt",10);
    jSONObject.put("unit",  17500);
    jSONObject.put("price",  175000);
    jSONObject.put("quiz","PBP, 피봇 기능을 갖춘 UHD 초고해상도 화면의 27형 모니터는?");
    jSONObject.put("ex1","삼성 C27F390");
    jSONObject.put("ex2","뷰소닉 VX2776");
    jSONObject.put("ex3","LG 27UD88");
    jSONObject.put("answer",3);
    jSONArray.put(jSONObject);
    
    out.println(jSONArray.toString());
    
%>